#!/bin/bash

function print_help {
	echo "crontabgen.sh -s <source_directory> -t <target_file>"
}

SOURCE=''
TARGET=''

while getopts ":s:t:" opt; do
	case $opt in
		s)
			SOURCE=$OPTARG
			;;
		t)
			TARGET=$OPTARG
			;;
		\?)
			echo "Invalid argument" >&2
			print_help
			;;
	esac
done

echo "$SOURCE"
if [ "$SOURCE" == '' ]; then
	echo "source_directory not specified"
	print_help
	exit 2
fi

echo "$TARGET"
if [ "$TARGET" == '' ]; then
	echo "target_file not specified"
	print_help
	exit 2
fi

if [ ! -d "$SOURCE" ]; then
	echo "Source is not directory"
	print_help
	exit 2
fi

if [ ! -f "$TARGET" ]; then
	echo "Target is not file"
	print_help
	exit 2
fi

echo '# Autogenerated crontab file by crontabgen' > $TARGET
find $SOURCE -type f -name "*.cron" -exec cat {} >> $TARGET \;
